M48
; DRILL file {KiCad 7.0.7} date Tue 12 Sep 2023 01:41:10 AM JST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-09-12T01:41:10+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X0.9843Y-0.9803
X0.9843Y-3.3425
X4.9213Y-0.9803
X4.9213Y-3.3425
T0
M30
